class Xpath_department:
    department = '/html/body/div/div[1]/div[2]/div/nav/div[2]/a[20]/span[1]/i'
    search = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[1]/span/span/div/input'
    id = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/thead/tr/th[1]'
    name = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/thead/tr/th[2]'
    photo = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/thead/tr/th[3]'
    coverphoto = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/thead/tr/th[4]'
    active = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/thead/tr/th[5]'
    date = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/thead/tr/th[6]'
    first_product_name = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/tbody/tr/td[2]'
    second_name = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/tbody/tr[2]/td[2]'
    first_id = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/tbody/tr[1]/td[1]'

    second_id = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/tbody/tr[2]/td[1]'
    first_image = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/tbody/tr[1]/td[3]/div/img'
    first_coverimage = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/tbody/tr[1]/td[4]/div/img'
    first_active = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/tbody/tr[1]/td[5]'
    first_date = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/tbody/tr[1]/td[6]/div'
    second_date = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[2]/div[1]/table/tbody/tr[2]/td[6]/div'
    dropdown = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[1]/div'
    add = '/html/body/div/div[1]/div[2]/main/div[2]/div/div[1]/div[2]/div/div[1]/span[2]'
    fill_new_name = '/html/body/div/div[1]/div[4]/div/div/form/div[1]/div[1]/span/div/input'
    add_department = '/html/body/div/div[1]/div[4]/div/div/form/input'

